### ISSUE TITLE
help

### ISSUE THREAD

**Issue by raviteja10081996** [davFaithid/pokemon-tv#1]
i like your project how do it on mac

**Comment by davFaithid** [comment]
I have not thought of using it on a mac (and I don't know where to begin with using python on a mac). So maybe try installing https://github.com/Ivshti/libmpv/blob/master/mac/lib/libmpv.1.dylib to path, run the code and then if it doesn't work please get back to me. = )

**Comment by raviteja10081996** [comment]
WILL TRY 
THANK YOU
